theme: jekyll-theme-minimal

title: Image Collections
description: Comic book store in Mississauga
logo: /assets/img/logo.png

show_downloads: false
footer: true

# GitHub Pages settings
repository: image-collections/image-collections.github.io
